import { ImageSource } from "expo-image";

const cookwareImages: Record<string, ImageSource> = {
  "air fryer": require("./air_fryer_illustration.png"),
  "baking sheet": require("./baking_sheet_illustration.png"),
  blender: require("./blender_illustration.png"),
  "bread knife": require("./bread_knife_illustration.png"),
  "bread machine": require("./bread_machine_illustration.png"),
  "cake pan": require("./cake_pan_illustration.png"),
  "can opener": require("./can_opener_illustration.png"),
  "casserole dish": require("./casserole_dish_illustration.png"),
  "chef's knife": require("./chef_knife_illustration.png"),
  "coffee maker": require("./coffee_maker_illustration.png"),
  colander: require("./colander_illustration.png"),
  "cooling rack": require("./cooling_rack_illustration.png"),
  "cutting board": require("./cutting_board_illustration.png"),
  dehydrator: require("./dehydrator_illustration.png"),
  "dutch oven": require("./dutch_oven_illustration.png"),
  "food processor": require("./food_processor_illustration.png"),
  freezer: require("./freezer_illustration.png"),
  "frying pan/skillet": require("./frying_pan_illustration.png"),
  grater: require("./grater_illustration.png"),
  "grill pan": require("./grill_pan_illustration.png"),
  "hand mixer": require("./hand_mixer_illustration.png"),
  "ice cream maker": require("./ice_cream_maker_illustration.png"),
  "immersion blender": require("./immersion_blender_illustration.png"),
  "instant pot/pressure cooker": require("./instant_pot_illustration.png"),
  kettle: require("./electric_kettle_illustration.png"),
  "kitchenaid attachments": require("./kitchenaid_attachments_illustration.png"),
  "kitchen shears": require("./kitchen_shears_illustration.png"),
  ladle: require("./ladle_illustration.png"),
  "loaf pan": require("./loaf_pan_illustration.png"),
  "measuring cups": require("./measuring_cups_illustration.png"),
  "measuring spoons": require("./measuring_spoons_illustration.png"),
  microwave: require("./microwave_illustration.png"),
  "mixing bowls": require("./mixing_bowls_illustration.png"),
  "muffin tin": require("./muffin_tin_illustration.png"),
  oven: require("./oven_illustration.png"),
  "panini press": require("./panini_press_illustration.png"),
  "paring knife": require("./paring_knife_illustration.png"),
  "pasta machine": require("./pasta_machine_illustration.png"),
  peeler: require("./peeler_illustration.png"),
  "pie dish": require("./pie_dish_illustration.png"),
  refrigerator: require("./refrigerator_illustration.png"),
  "rice cooker": require("./rice_cooker_illustration.png"),
  "roasting pan": require("./roasting_pan_illustration.png"),
  "saucepan (small, medium, large)": require("./saucepan_illustration.png"),
  sink: require("./kitchen_sink_illustration.png"),
  "slow cooker/crock pot": require("./slow_cooker_illustration.png"),
  "sous vide": require("./sous_vide_illustration.png"),
  spatula: require("./spatula_illustration.png"),
  "stand mixer": require("./stand_mixer_illustration.png"),
  "stock pot": require("./stock_pot_illustration.png"),
  "stovetop/range": require("./stovetop_illustration.png"),
  thermomix: require("./thermomix_illustration.png"),
  toaster: require("./toaster_illustration.png"),
  tongs: require("./tongs_illustration.png"),
  "waffle maker": require("./waffle_maker_illustration.png"),
  whisk: require("./whisk_illustration.png"),
  wok: require("./wok_illustration.png"),
  "wooden spoon": require("./wooden_spoon_illustration.png"),
};

export function getCookwareImage(name: string): ImageSource | null {
  const normalizedName = name.toLowerCase().trim();
  return cookwareImages[normalizedName] || null;
}

export default cookwareImages;
