import {
  StyleSheet,
  View,
  Text,
  ScrollView,
  Pressable,
  Platform,
  Image,
} from "react-native";
import { AnimatedBackground } from "@/components/AnimatedBackground";
import { WebInfoColors } from "@/constants/theme";

const isWeb = Platform.OS === "web";
const chefHatLight = require("../../assets/images/transparent/chef-hat-light-128.png");

const NAV_LINKS = [
  { label: "Home", path: "/" },
  { label: "About", path: "/about" },
  { label: "Privacy", path: "/privacy" },
  { label: "Terms", path: "/terms" },
  { label: "Support", path: "/support" },
];

export default function TermsScreen() {
  const colors = WebInfoColors;
  const currentPath = "/terms";

  const navigateTo = (path: string) => {
    if (isWeb && typeof window !== "undefined") {
      window.history.pushState({}, "", path);
      window.dispatchEvent(new PopStateEvent("popstate"));
    }
  };

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.contentContainer}
    >
      <AnimatedBackground />

      {isWeb && (
        <View style={styles.header}>
          <Pressable
            style={styles.logoContainer}
            onPress={() => navigateTo("/")}
          >
            <Image
              source={chefHatLight}
              style={{ width: 32, height: 32 }}
              resizeMode="contain"
              accessibilityElementsHidden={true}
              importantForAccessibility="no-hide-descendants"
            />
            <Text style={[styles.logoText, { color: colors.textPrimary }]}>
              ChefSpAIce
            </Text>
          </Pressable>
          <View style={styles.navLinks}>
            {NAV_LINKS.map((link) => (
              <Pressable
                key={link.path}
                onPress={() => navigateTo(link.path)}
                style={styles.navLink}
                data-testid={`nav-link-${link.label.toLowerCase()}`}
              >
                <Text
                  style={[
                    styles.navLinkText,
                    {
                      color:
                        currentPath === link.path
                          ? colors.brandGreen
                          : colors.textSecondary,
                    },
                  ]}
                >
                  {link.label}
                </Text>
              </Pressable>
            ))}
          </View>
        </View>
      )}

      <View style={styles.content}>
        <Text style={[styles.title, { color: colors.textPrimary }]}>
          Terms of Service
        </Text>
        <Text style={[styles.lastUpdated, { color: colors.textMuted }]}>
          Last updated: January 2026
        </Text>

        <View
          style={[
            styles.card,
            { backgroundColor: colors.card, borderColor: colors.cardBorder },
          ]}
        >
          <Text style={[styles.sectionTitle, { color: colors.textPrimary }]}>
            Acceptance of Terms
          </Text>
          <Text style={[styles.paragraph, { color: colors.textSecondary }]}>
            By accessing or using ChefSpAIce, you agree to be bound by these
            Terms of Service. If you do not agree to these terms, please do not
            use our application.
          </Text>
        </View>

        <View
          style={[
            styles.card,
            { backgroundColor: colors.card, borderColor: colors.cardBorder },
          ]}
        >
          <Text style={[styles.sectionTitle, { color: colors.textPrimary }]}>
            Use of Service
          </Text>
          <Text style={[styles.paragraph, { color: colors.textSecondary }]}>
            ChefSpAIce is provided for personal, non-commercial use. You agree
            to use the service responsibly and not to misuse or attempt to
            exploit any features of the application.
          </Text>
        </View>

        <View
          style={[
            styles.card,
            { backgroundColor: colors.card, borderColor: colors.cardBorder },
          ]}
        >
          <Text style={[styles.sectionTitle, { color: colors.textPrimary }]}>
            AI-Generated Content
          </Text>
          <Text style={[styles.paragraph, { color: colors.textSecondary }]}>
            Recipes generated by our AI are provided for informational purposes
            only. While we strive for accuracy, we cannot guarantee that all
            recipes are safe for individuals with specific allergies or dietary
            restrictions. Always verify ingredients before cooking.
          </Text>
        </View>

        <View
          style={[
            styles.card,
            { backgroundColor: colors.card, borderColor: colors.cardBorder },
          ]}
        >
          <Text style={[styles.sectionTitle, { color: colors.textPrimary }]}>
            Limitation of Liability
          </Text>
          <Text style={[styles.paragraph, { color: colors.textSecondary }]}>
            ChefSpAIce is provided "as is" without warranties of any kind. We
            are not liable for any damages arising from your use of the
            application, including but not limited to food safety issues or
            inaccurate expiration tracking.
          </Text>
        </View>

        <View
          style={[
            styles.card,
            { backgroundColor: colors.card, borderColor: colors.cardBorder },
          ]}
        >
          <Text style={[styles.sectionTitle, { color: colors.textPrimary }]}>
            Subscriptions and Payments
          </Text>
          <Text style={[styles.paragraph, { color: colors.textSecondary }]}>
            ChefSpAIce offers auto-renewable subscription options to access
            premium features. By purchasing a subscription, you agree to the
            following terms:
          </Text>
          <Text
            style={[
              styles.paragraph,
              { color: colors.textSecondary, marginTop: 12 },
            ]}
          >
            <Text style={{ fontWeight: "600" }}>Payment:</Text> Payment will be
            charged to your Apple ID account at confirmation of purchase.
          </Text>
          <Text
            style={[
              styles.paragraph,
              { color: colors.textSecondary, marginTop: 12 },
            ]}
          >
            <Text style={{ fontWeight: "600" }}>Renewal:</Text> Subscriptions
            automatically renew unless auto-renew is turned off at least 24
            hours before the end of the current subscription period. Your
            account will be charged for renewal within 24 hours prior to the
            end of the current period at the same price.
          </Text>
          <Text
            style={[
              styles.paragraph,
              { color: colors.textSecondary, marginTop: 12 },
            ]}
          >
            <Text style={{ fontWeight: "600" }}>Managing Subscriptions:</Text>{" "}
            You can manage and cancel your subscriptions by going to your
            Account Settings in the App Store after purchase. Any unused
            portion of a free trial period will be forfeited when you purchase
            a subscription.
          </Text>
          <Text
            style={[
              styles.paragraph,
              { color: colors.textSecondary, marginTop: 12 },
            ]}
          >
            <Text style={{ fontWeight: "600" }}>Refunds:</Text> Refunds are
            handled by Apple in accordance with their refund policies. To
            request a refund, please visit Apple's Report a Problem page or
            contact Apple Support directly.
          </Text>
        </View>

        <View
          style={[
            styles.card,
            { backgroundColor: colors.card, borderColor: colors.cardBorder },
          ]}
        >
          <Text style={[styles.sectionTitle, { color: colors.textPrimary }]}>
            Contact Us
          </Text>
          <Text style={[styles.paragraph, { color: colors.textSecondary }]}>
            If you have any questions about these Terms of Service, please
            contact us through our Support page.
          </Text>
        </View>
      </View>

      {isWeb && (
        <View style={[styles.footer, { backgroundColor: colors.footerBg }]}>
          <Text style={[styles.copyright, { color: colors.textMuted }]}>
            © {new Date().getFullYear()} ChefSpAIce. All rights reserved.
          </Text>
        </View>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  contentContainer: { minHeight: "100%" },
  header: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 12,
    alignItems: "center",
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    cursor: "pointer" as any,
    marginBottom: 16,
  },
  logoText: { fontSize: 24, fontWeight: "700" },
  navLinks: {
    flexDirection: "row",
    alignItems: "center",
    gap: 24,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  navLink: { cursor: "pointer" as any },
  navLinkText: { fontSize: 14, fontWeight: "500" },
  content: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 60,
    maxWidth: 800,
    alignSelf: "center",
    width: "100%",
  },
  title: {
    fontSize: 42,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 8,
  },
  lastUpdated: { fontSize: 14, textAlign: "center", marginBottom: 40 },
  card: { borderRadius: 16, padding: 24, borderWidth: 1, marginBottom: 24 },
  sectionTitle: { fontSize: 22, fontWeight: "600", marginBottom: 12 },
  paragraph: { fontSize: 16, lineHeight: 26 },
  footer: { paddingVertical: 32, paddingHorizontal: 24, alignItems: "center" },
  copyright: { fontSize: 12 },
});
