import { Feather } from "@expo/vector-icons";
import { NutritionInfo } from "@/lib/storage";
import { WithSpringConfig } from "react-native-reanimated";

export interface Appliance {
  id: number;
  name: string;
  category: string;
  description: string;
  icon: string;
  isCommon: boolean;
  alternatives: string[];
}

export interface StarterFood {
  id: string;
  name: string;
  category: string;
  recommendedStorage: "fridge" | "freezer" | "pantry" | "counter";
  defaultQuantity: number;
  unit: string;
  shelfLifeDays: number;
  icon: keyof typeof Feather.glyphMap;
  fdcId: number;
  nutrition?: NutritionInfo;
}

export const STARTER_FOODS: StarterFood[] = [
  {
    id: "milk",
    name: "Milk, whole",
    category: "Dairy and Egg Products",
    recommendedStorage: "fridge",
    defaultQuantity: 1,
    unit: "gallon",
    shelfLifeDays: 7,
    icon: "droplet",
    fdcId: 746776,
    nutrition: {
      calories: 61,
      protein: 3.15,
      carbs: 4.78,
      fat: 3.27,
      fiber: 0,
      sugar: 5.05,
      sodium: 43,
      servingSize: "100g",
    },
  },
  {
    id: "eggs",
    name: "Egg, whole, raw",
    category: "Dairy and Egg Products",
    recommendedStorage: "fridge",
    defaultQuantity: 12,
    unit: "count",
    shelfLifeDays: 21,
    icon: "circle",
    fdcId: 748967,
    nutrition: {
      calories: 143,
      protein: 12.56,
      carbs: 0.72,
      fat: 9.51,
      fiber: 0,
      sugar: 0.37,
      sodium: 142,
      servingSize: "100g",
    },
  },
  {
    id: "butter",
    name: "Butter, salted",
    category: "Fats and Oils",
    recommendedStorage: "fridge",
    defaultQuantity: 1,
    unit: "stick",
    shelfLifeDays: 30,
    icon: "square",
    fdcId: 173410,
    nutrition: {
      calories: 717,
      protein: 0.85,
      carbs: 0.06,
      fat: 81.11,
      fiber: 0,
      sugar: 0.06,
      sodium: 643,
      servingSize: "100g",
    },
  },
  {
    id: "cheese",
    name: "Cheese, cheddar",
    category: "Dairy and Egg Products",
    recommendedStorage: "fridge",
    defaultQuantity: 8,
    unit: "oz",
    shelfLifeDays: 21,
    icon: "grid",
    fdcId: 173414,
    nutrition: {
      calories: 403,
      protein: 22.87,
      carbs: 3.09,
      fat: 33.31,
      fiber: 0,
      sugar: 0.48,
      sodium: 653,
      servingSize: "100g",
    },
  },
  {
    id: "yogurt",
    name: "Yogurt, plain, whole milk",
    category: "Dairy and Egg Products",
    recommendedStorage: "fridge",
    defaultQuantity: 1,
    unit: "container",
    shelfLifeDays: 14,
    icon: "circle",
    fdcId: 171284,
    nutrition: {
      calories: 61,
      protein: 3.47,
      carbs: 4.66,
      fat: 3.25,
      fiber: 0,
      sugar: 4.66,
      sodium: 46,
      servingSize: "100g",
    },
  },
  {
    id: "bread",
    name: "Bread, white, commercially prepared",
    category: "Baked Products",
    recommendedStorage: "counter",
    defaultQuantity: 1,
    unit: "loaf",
    shelfLifeDays: 5,
    icon: "box",
    fdcId: 172687,
    nutrition: {
      calories: 266,
      protein: 7.64,
      carbs: 50.61,
      fat: 3.29,
      fiber: 2.3,
      sugar: 5.34,
      sodium: 477,
      servingSize: "100g",
    },
  },
  {
    id: "rice",
    name: "Rice, white, long-grain, regular, raw",
    category: "Cereal Grains and Pasta",
    recommendedStorage: "pantry",
    defaultQuantity: 1,
    unit: "lb",
    shelfLifeDays: 365,
    icon: "layers",
    fdcId: 169756,
    nutrition: {
      calories: 365,
      protein: 7.13,
      carbs: 79.95,
      fat: 0.66,
      fiber: 1.3,
      sugar: 0.12,
      sodium: 5,
      servingSize: "100g",
    },
  },
  {
    id: "pasta",
    name: "Pasta, dry, enriched",
    category: "Cereal Grains and Pasta",
    recommendedStorage: "pantry",
    defaultQuantity: 1,
    unit: "lb",
    shelfLifeDays: 365,
    icon: "layers",
    fdcId: 168936,
    nutrition: {
      calories: 371,
      protein: 13.04,
      carbs: 74.67,
      fat: 1.51,
      fiber: 3.2,
      sugar: 2.67,
      sodium: 6,
      servingSize: "100g",
    },
  },
  {
    id: "chicken",
    name: "Chicken, broilers or fryers, breast, meat only, raw",
    category: "Poultry Products",
    recommendedStorage: "fridge",
    defaultQuantity: 1,
    unit: "lb",
    shelfLifeDays: 2,
    icon: "disc",
    fdcId: 171477,
    nutrition: {
      calories: 120,
      protein: 22.5,
      carbs: 0,
      fat: 2.62,
      fiber: 0,
      sugar: 0,
      sodium: 45,
      servingSize: "100g",
    },
  },
  {
    id: "ground_beef",
    name: "Beef, ground, 80% lean meat / 20% fat, raw",
    category: "Beef Products",
    recommendedStorage: "fridge",
    defaultQuantity: 1,
    unit: "lb",
    shelfLifeDays: 2,
    icon: "disc",
    fdcId: 174036,
    nutrition: {
      calories: 254,
      protein: 17.17,
      carbs: 0,
      fat: 20,
      fiber: 0,
      sugar: 0,
      sodium: 75,
      servingSize: "100g",
    },
  },
  {
    id: "apples",
    name: "Apples, raw, with skin",
    category: "Fruits and Fruit Juices",
    recommendedStorage: "fridge",
    defaultQuantity: 4,
    unit: "count",
    shelfLifeDays: 21,
    icon: "circle",
    fdcId: 171688,
    nutrition: {
      calories: 52,
      protein: 0.26,
      carbs: 13.81,
      fat: 0.17,
      fiber: 2.4,
      sugar: 10.39,
      sodium: 1,
      servingSize: "100g",
    },
  },
  {
    id: "bananas",
    name: "Bananas, raw",
    category: "Fruits and Fruit Juices",
    recommendedStorage: "counter",
    defaultQuantity: 1,
    unit: "bunch",
    shelfLifeDays: 5,
    icon: "moon",
    fdcId: 173944,
    nutrition: {
      calories: 89,
      protein: 1.09,
      carbs: 22.84,
      fat: 0.33,
      fiber: 2.6,
      sugar: 12.23,
      sodium: 1,
      servingSize: "100g",
    },
  },
  {
    id: "onions",
    name: "Onions, raw",
    category: "Vegetables and Vegetable Products",
    recommendedStorage: "pantry",
    defaultQuantity: 3,
    unit: "count",
    shelfLifeDays: 30,
    icon: "circle",
    fdcId: 170000,
    nutrition: {
      calories: 40,
      protein: 1.1,
      carbs: 9.34,
      fat: 0.1,
      fiber: 1.7,
      sugar: 4.24,
      sodium: 4,
      servingSize: "100g",
    },
  },
  {
    id: "potatoes",
    name: "Potatoes, flesh and skin, raw",
    category: "Vegetables and Vegetable Products",
    recommendedStorage: "pantry",
    defaultQuantity: 5,
    unit: "count",
    shelfLifeDays: 21,
    icon: "box",
    fdcId: 170026,
    nutrition: {
      calories: 77,
      protein: 2.05,
      carbs: 17.49,
      fat: 0.09,
      fiber: 2.1,
      sugar: 0.82,
      sodium: 6,
      servingSize: "100g",
    },
  },
  {
    id: "tomatoes",
    name: "Tomatoes, red, ripe, raw",
    category: "Vegetables and Vegetable Products",
    recommendedStorage: "counter",
    defaultQuantity: 3,
    unit: "count",
    shelfLifeDays: 5,
    icon: "circle",
    fdcId: 170457,
    nutrition: {
      calories: 18,
      protein: 0.88,
      carbs: 3.89,
      fat: 0.2,
      fiber: 1.2,
      sugar: 2.63,
      sodium: 5,
      servingSize: "100g",
    },
  },
  {
    id: "carrots",
    name: "Carrots, raw",
    category: "Vegetables and Vegetable Products",
    recommendedStorage: "fridge",
    defaultQuantity: 1,
    unit: "lb",
    shelfLifeDays: 21,
    icon: "zap",
    fdcId: 170393,
    nutrition: {
      calories: 41,
      protein: 0.93,
      carbs: 9.58,
      fat: 0.24,
      fiber: 2.8,
      sugar: 4.74,
      sodium: 69,
      servingSize: "100g",
    },
  },
  {
    id: "broccoli",
    name: "Broccoli, raw",
    category: "Vegetables and Vegetable Products",
    recommendedStorage: "fridge",
    defaultQuantity: 1,
    unit: "head",
    shelfLifeDays: 7,
    icon: "cloud",
    fdcId: 170379,
    nutrition: {
      calories: 34,
      protein: 2.82,
      carbs: 6.64,
      fat: 0.37,
      fiber: 2.6,
      sugar: 1.7,
      sodium: 33,
      servingSize: "100g",
    },
  },
  {
    id: "orange_juice",
    name: "Orange juice, raw",
    category: "Fruits and Fruit Juices",
    recommendedStorage: "fridge",
    defaultQuantity: 1,
    unit: "carton",
    shelfLifeDays: 7,
    icon: "sun",
    fdcId: 169098,
    nutrition: {
      calories: 45,
      protein: 0.7,
      carbs: 10.4,
      fat: 0.2,
      fiber: 0.2,
      sugar: 8.4,
      sodium: 1,
      servingSize: "100g",
    },
  },
];

export const STORAGE_LABELS: Record<
  string,
  { label: string; color: string; icon: keyof typeof Feather.glyphMap }
> = {
  fridge: { label: "Fridge", color: "#3B82F6", icon: "box" },
  freezer: { label: "Freezer", color: "#8B5CF6", icon: "thermometer" },
  pantry: { label: "Pantry", color: "#F59E0B", icon: "archive" },
  counter: { label: "Counter", color: "#10B981", icon: "grid" },
};

export const EQUIPMENT_CATEGORIES = [
  {
    id: "essential",
    label: "Essential",
    icon: "home",
    description: "Basic kitchen items everyone needs",
  },
  {
    id: "cooking",
    label: "Cooking",
    icon: "thermometer",
    description: "Pots, pans, and cooking surfaces",
  },
  {
    id: "bakeware",
    label: "Bakeware",
    icon: "square",
    description: "Baking sheets, pans, and molds",
  },
  {
    id: "small appliances",
    label: "Small Appliances",
    icon: "zap",
    description: "Electric kitchen helpers",
  },
  {
    id: "prep tools",
    label: "Prep Tools",
    icon: "tool",
    description: "Cutting, mixing, and measuring",
  },
  {
    id: "specialty",
    label: "Specialty",
    icon: "star",
    description: "Special equipment for specific dishes",
  },
] as const;

export const ICON_MAP: Record<string, keyof typeof Feather.glyphMap> = {
  thermometer: "thermometer",
  box: "box",
  zap: "zap",
  circle: "circle",
  square: "square",
  droplet: "droplet",
  coffee: "coffee",
  tool: "tool",
  layers: "layers",
  grid: "grid",
  package: "package",
  disc: "disc",
  clipboard: "clipboard",
  target: "target",
  filter: "filter",
  scissors: "scissors",
  edit3: "edit-3",
  sliders: "sliders",
  aperture: "aperture",
  watch: "watch",
  activity: "activity",
  wind: "wind",
  home: "home",
  star: "star",
  default: "box",
};

export const springConfig: WithSpringConfig = {
  damping: 15,
  mass: 0.3,
  stiffness: 150,
  overshootClamping: true,
};

export type OnboardingStep =
  | "welcome"
  | "preferences"
  | "storage"
  | "foods"
  | "cookware"
  | "complete";

export const SERVING_SIZE_OPTIONS = [
  { value: 1, label: "Just me" },
  { value: 2, label: "2 people" },
  { value: 3, label: "3 people" },
  { value: 4, label: "4 people" },
  { value: 5, label: "5 people" },
  { value: 6, label: "6+ people" },
];

export const DAILY_MEALS_OPTIONS = [
  { value: 2, label: "2 meals" },
  { value: 3, label: "3 meals" },
  { value: 4, label: "4 meals" },
  { value: 5, label: "5+ meals" },
];

export const CUISINE_OPTIONS = [
  { id: "american", label: "American", icon: "flag" as const },
  { id: "italian", label: "Italian", icon: "coffee" as const },
  { id: "mexican", label: "Mexican", icon: "sun" as const },
  { id: "asian", label: "Asian", icon: "sunrise" as const },
  { id: "mediterranean", label: "Mediterranean", icon: "droplet" as const },
  { id: "indian", label: "Indian", icon: "zap" as const },
  { id: "french", label: "French", icon: "feather" as const },
  { id: "japanese", label: "Japanese", icon: "circle" as const },
  { id: "chinese", label: "Chinese", icon: "star" as const },
  { id: "thai", label: "Thai", icon: "heart" as const },
  { id: "korean", label: "Korean", icon: "moon" as const },
  { id: "greek", label: "Greek", icon: "compass" as const },
];

export const DIETARY_PREFERENCE_OPTIONS = [
  { id: "none", label: "No restrictions", icon: "check-circle" as const },
  { id: "vegetarian", label: "Vegetarian", icon: "feather" as const },
  { id: "vegan", label: "Vegan", icon: "sun" as const },
  { id: "pescatarian", label: "Pescatarian", icon: "anchor" as const },
  { id: "gluten-free", label: "Gluten-Free", icon: "slash" as const },
  { id: "dairy-free", label: "Dairy-Free", icon: "x-circle" as const },
  { id: "keto", label: "Keto", icon: "activity" as const },
  { id: "paleo", label: "Paleo", icon: "target" as const },
  { id: "halal", label: "Halal", icon: "moon" as const },
  { id: "kosher", label: "Kosher", icon: "star" as const },
];

export const DEFAULT_STORAGE_AREAS = [
  {
    id: "fridge",
    label: "Refrigerator",
    icon: "thermometer" as const,
    description: "For perishable items",
  },
  {
    id: "freezer",
    label: "Freezer",
    icon: "cloud-snow" as const,
    description: "For frozen goods",
  },
  {
    id: "pantry",
    label: "Pantry",
    icon: "box" as const,
    description: "For dry goods & canned items",
  },
  {
    id: "counter",
    label: "Counter",
    icon: "home" as const,
    description: "For fruits & daily items",
  },
];
