export interface StarterFood {
  name: string;
  category: string;
  defaultStorage: "refrigerator" | "freezer" | "pantry" | "counter";
  defaultShelfLifeDays: number;
  fdcId?: number;
  isCommon: boolean;
}

export const STARTER_FOODS: StarterFood[] = [
  // DAIRY - Refrigerator
  {
    name: "Milk",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 7,
    fdcId: 171265,
    isCommon: true,
  },
  {
    name: "Butter",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 30,
    fdcId: 173430,
    isCommon: true,
  },
  {
    name: "Eggs",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 21,
    fdcId: 171287,
    isCommon: true,
  },
  {
    name: "Cheddar Cheese",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 28,
    fdcId: 173414,
    isCommon: true,
  },
  {
    name: "Greek Yogurt",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 14,
    fdcId: 170903,
    isCommon: true,
  },
  {
    name: "Cream Cheese",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 14,
    fdcId: 173417,
    isCommon: false,
  },
  {
    name: "Sour Cream",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 14,
    fdcId: 173419,
    isCommon: false,
  },
  {
    name: "Heavy Cream",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 10,
    fdcId: 173416,
    isCommon: false,
  },
  {
    name: "Parmesan Cheese",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 42,
    fdcId: 173420,
    isCommon: true,
  },
  {
    name: "Mozzarella Cheese",
    category: "Dairy",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 14,
    fdcId: 173421,
    isCommon: true,
  },

  // PRODUCE - Refrigerator
  {
    name: "Lettuce",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 7,
    fdcId: 169248,
    isCommon: true,
  },
  {
    name: "Carrots",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 21,
    fdcId: 170393,
    isCommon: true,
  },
  {
    name: "Celery",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 14,
    fdcId: 169988,
    isCommon: true,
  },
  {
    name: "Bell Peppers",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 10,
    fdcId: 170108,
    isCommon: true,
  },
  {
    name: "Broccoli",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 7,
    fdcId: 170379,
    isCommon: true,
  },
  {
    name: "Spinach",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 5,
    fdcId: 168462,
    isCommon: true,
  },
  {
    name: "Cucumber",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 7,
    fdcId: 168409,
    isCommon: true,
  },
  {
    name: "Zucchini",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 7,
    fdcId: 169291,
    isCommon: false,
  },
  {
    name: "Mushrooms",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 7,
    fdcId: 169242,
    isCommon: true,
  },
  {
    name: "Green Beans",
    category: "Vegetables",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 7,
    fdcId: 169961,
    isCommon: false,
  },

  // PRODUCE - Counter
  {
    name: "Bananas",
    category: "Fruits",
    defaultStorage: "counter",
    defaultShelfLifeDays: 5,
    fdcId: 173944,
    isCommon: true,
  },
  {
    name: "Apples",
    category: "Fruits",
    defaultStorage: "counter",
    defaultShelfLifeDays: 14,
    fdcId: 171688,
    isCommon: true,
  },
  {
    name: "Oranges",
    category: "Fruits",
    defaultStorage: "counter",
    defaultShelfLifeDays: 10,
    fdcId: 169097,
    isCommon: true,
  },
  {
    name: "Lemons",
    category: "Fruits",
    defaultStorage: "counter",
    defaultShelfLifeDays: 14,
    fdcId: 167747,
    isCommon: true,
  },
  {
    name: "Limes",
    category: "Fruits",
    defaultStorage: "counter",
    defaultShelfLifeDays: 14,
    fdcId: 168155,
    isCommon: false,
  },
  {
    name: "Avocados",
    category: "Fruits",
    defaultStorage: "counter",
    defaultShelfLifeDays: 4,
    fdcId: 171705,
    isCommon: true,
  },
  {
    name: "Tomatoes",
    category: "Vegetables",
    defaultStorage: "counter",
    defaultShelfLifeDays: 7,
    fdcId: 170457,
    isCommon: true,
  },
  {
    name: "Onions",
    category: "Vegetables",
    defaultStorage: "counter",
    defaultShelfLifeDays: 30,
    fdcId: 170000,
    isCommon: true,
  },
  {
    name: "Garlic",
    category: "Vegetables",
    defaultStorage: "counter",
    defaultShelfLifeDays: 60,
    fdcId: 169230,
    isCommon: true,
  },
  {
    name: "Potatoes",
    category: "Vegetables",
    defaultStorage: "counter",
    defaultShelfLifeDays: 21,
    fdcId: 170026,
    isCommon: true,
  },

  // PROTEINS - Refrigerator
  {
    name: "Chicken Breast",
    category: "Meat",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 2,
    fdcId: 171077,
    isCommon: true,
  },
  {
    name: "Ground Beef",
    category: "Meat",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 2,
    fdcId: 174032,
    isCommon: true,
  },
  {
    name: "Bacon",
    category: "Meat",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 7,
    fdcId: 168322,
    isCommon: true,
  },
  {
    name: "Salmon",
    category: "Seafood",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 2,
    fdcId: 175168,
    isCommon: true,
  },
  {
    name: "Shrimp",
    category: "Seafood",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 2,
    fdcId: 175180,
    isCommon: false,
  },
  {
    name: "Deli Turkey",
    category: "Meat",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 5,
    fdcId: 174608,
    isCommon: true,
  },
  {
    name: "Deli Ham",
    category: "Meat",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 5,
    fdcId: 174571,
    isCommon: false,
  },

  // PROTEINS - Freezer
  {
    name: "Frozen Chicken",
    category: "Meat",
    defaultStorage: "freezer",
    defaultShelfLifeDays: 270,
    fdcId: 171077,
    isCommon: true,
  },
  {
    name: "Frozen Ground Beef",
    category: "Meat",
    defaultStorage: "freezer",
    defaultShelfLifeDays: 120,
    fdcId: 174032,
    isCommon: true,
  },
  {
    name: "Frozen Fish Fillets",
    category: "Seafood",
    defaultStorage: "freezer",
    defaultShelfLifeDays: 180,
    fdcId: 171955,
    isCommon: true,
  },
  {
    name: "Frozen Shrimp",
    category: "Seafood",
    defaultStorage: "freezer",
    defaultShelfLifeDays: 180,
    fdcId: 175180,
    isCommon: false,
  },

  // FROZEN ITEMS
  {
    name: "Frozen Vegetables",
    category: "Vegetables",
    defaultStorage: "freezer",
    defaultShelfLifeDays: 240,
    fdcId: 169369,
    isCommon: true,
  },
  {
    name: "Frozen Berries",
    category: "Fruits",
    defaultStorage: "freezer",
    defaultShelfLifeDays: 240,
    fdcId: 171711,
    isCommon: true,
  },
  {
    name: "Ice Cream",
    category: "Dairy",
    defaultStorage: "freezer",
    defaultShelfLifeDays: 60,
    fdcId: 167575,
    isCommon: true,
  },
  {
    name: "Frozen Pizza",
    category: "Prepared Foods",
    defaultStorage: "freezer",
    defaultShelfLifeDays: 60,
    fdcId: 173291,
    isCommon: false,
  },

  // PANTRY - Grains & Starches
  {
    name: "White Rice",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 169756,
    isCommon: true,
  },
  {
    name: "Brown Rice",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 180,
    fdcId: 169702,
    isCommon: true,
  },
  {
    name: "Pasta",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 168927,
    isCommon: true,
  },
  {
    name: "Bread",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 7,
    fdcId: 172686,
    isCommon: true,
  },
  {
    name: "Flour",
    category: "Baking",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 169761,
    isCommon: true,
  },
  {
    name: "Oatmeal",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 173904,
    isCommon: true,
  },
  {
    name: "Cereal",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 180,
    fdcId: 173901,
    isCommon: true,
  },
  {
    name: "Tortillas",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 14,
    fdcId: 168013,
    isCommon: true,
  },
  {
    name: "Crackers",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 180,
    fdcId: 173191,
    isCommon: false,
  },
  {
    name: "Quinoa",
    category: "Grains",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 168874,
    isCommon: false,
  },

  // PANTRY - Canned Goods
  {
    name: "Canned Tomatoes",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 170462,
    isCommon: true,
  },
  {
    name: "Canned Beans",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 175197,
    isCommon: true,
  },
  {
    name: "Canned Corn",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 169998,
    isCommon: true,
  },
  {
    name: "Canned Tuna",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 1095,
    fdcId: 171989,
    isCommon: true,
  },
  {
    name: "Chicken Broth",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 172193,
    isCommon: true,
  },
  {
    name: "Vegetable Broth",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 174283,
    isCommon: false,
  },
  {
    name: "Canned Soup",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 172181,
    isCommon: false,
  },
  {
    name: "Tomato Paste",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 170467,
    isCommon: true,
  },
  {
    name: "Coconut Milk",
    category: "Canned",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 170158,
    isCommon: false,
  },

  // PANTRY - Oils & Condiments
  {
    name: "Olive Oil",
    category: "Oils",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 171413,
    isCommon: true,
  },
  {
    name: "Vegetable Oil",
    category: "Oils",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 171016,
    isCommon: true,
  },
  {
    name: "Soy Sauce",
    category: "Condiments",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 1095,
    fdcId: 173472,
    isCommon: true,
  },
  {
    name: "Ketchup",
    category: "Condiments",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 174680,
    isCommon: true,
  },
  {
    name: "Mustard",
    category: "Condiments",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 172238,
    isCommon: true,
  },
  {
    name: "Mayonnaise",
    category: "Condiments",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 60,
    fdcId: 173585,
    isCommon: true,
  },
  {
    name: "Hot Sauce",
    category: "Condiments",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 1095,
    fdcId: 173578,
    isCommon: false,
  },
  {
    name: "Vinegar",
    category: "Condiments",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 1825,
    fdcId: 173468,
    isCommon: true,
  },
  {
    name: "Worcestershire Sauce",
    category: "Condiments",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 1095,
    fdcId: 173494,
    isCommon: false,
  },
  {
    name: "Honey",
    category: "Sweeteners",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 169640,
    isCommon: true,
  },

  // PANTRY - Baking
  {
    name: "Sugar",
    category: "Baking",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 169655,
    isCommon: true,
  },
  {
    name: "Brown Sugar",
    category: "Baking",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 168833,
    isCommon: true,
  },
  {
    name: "Baking Soda",
    category: "Baking",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 168920,
    isCommon: true,
  },
  {
    name: "Baking Powder",
    category: "Baking",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 168921,
    isCommon: true,
  },
  {
    name: "Vanilla Extract",
    category: "Baking",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 1825,
    fdcId: 168895,
    isCommon: true,
  },
  {
    name: "Chocolate Chips",
    category: "Baking",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 365,
    fdcId: 167587,
    isCommon: false,
  },

  // PANTRY - Spices & Seasonings
  {
    name: "Salt",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 1825,
    fdcId: 173467,
    isCommon: true,
  },
  {
    name: "Black Pepper",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 170929,
    isCommon: true,
  },
  {
    name: "Cinnamon",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 171320,
    isCommon: true,
  },
  {
    name: "Cumin",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 170924,
    isCommon: true,
  },
  {
    name: "Paprika",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 171329,
    isCommon: true,
  },
  {
    name: "Italian Seasoning",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 171331,
    isCommon: true,
  },
  {
    name: "Chili Powder",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 171318,
    isCommon: true,
  },
  {
    name: "Oregano",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 171328,
    isCommon: true,
  },
  {
    name: "Basil",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 172232,
    isCommon: true,
  },
  {
    name: "Garlic Powder",
    category: "Spices",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 171324,
    isCommon: true,
  },

  // PANTRY - Nuts & Seeds
  {
    name: "Peanut Butter",
    category: "Spreads",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 180,
    fdcId: 172470,
    isCommon: true,
  },
  {
    name: "Almonds",
    category: "Nuts",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 180,
    fdcId: 170567,
    isCommon: true,
  },
  {
    name: "Walnuts",
    category: "Nuts",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 180,
    fdcId: 170187,
    isCommon: false,
  },
  {
    name: "Cashews",
    category: "Nuts",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 180,
    fdcId: 170162,
    isCommon: false,
  },

  // BEVERAGES
  {
    name: "Orange Juice",
    category: "Beverages",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 10,
    fdcId: 169098,
    isCommon: true,
  },
  {
    name: "Apple Juice",
    category: "Beverages",
    defaultStorage: "refrigerator",
    defaultShelfLifeDays: 14,
    fdcId: 171687,
    isCommon: false,
  },
  {
    name: "Coffee",
    category: "Beverages",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 180,
    fdcId: 171891,
    isCommon: true,
  },
  {
    name: "Tea",
    category: "Beverages",
    defaultStorage: "pantry",
    defaultShelfLifeDays: 730,
    fdcId: 173230,
    isCommon: true,
  },
];

export function getCommonStarterFoods(): StarterFood[] {
  return STARTER_FOODS.filter((food) => food.isCommon);
}

export function getStarterFoodsByStorage(
  storage: StarterFood["defaultStorage"],
): StarterFood[] {
  return STARTER_FOODS.filter((food) => food.defaultStorage === storage);
}

export function getStarterFoodsByCategory(category: string): StarterFood[] {
  return STARTER_FOODS.filter(
    (food) => food.category.toLowerCase() === category.toLowerCase(),
  );
}
