import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { appliances } from "@shared/schema";

const APPLIANCES_DATA = [
  // ESSENTIAL (is_common: true)
  {
    name: "Stovetop/Range",
    category: "essential",
    description: "A cooking appliance with burners for heating pots and pans",
    icon: "thermometer",
    imageUrl: "/assets/appliances/stovetop_gas_range_b_7c27c369.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Oven",
    category: "essential",
    description: "An enclosed compartment for baking and roasting food",
    icon: "square",
    imageUrl: "/assets/appliances/modern_kitchen_oven__4c42404d.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Refrigerator",
    category: "essential",
    description: "An appliance for keeping food cold and fresh",
    icon: "box",
    imageUrl: "/assets/appliances/refrigerator_stainle_c29279f0.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Freezer",
    category: "essential",
    description: "An appliance for freezing and storing food long-term",
    icon: "box",
    imageUrl: "/assets/appliances/freezer_kitchen_appl_6f939d3e.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Microwave",
    category: "essential",
    description: "An appliance that heats food using electromagnetic radiation",
    icon: "zap",
    imageUrl: "/assets/appliances/microwave_kitchen_co_62a727ed.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Sink",
    category: "essential",
    description: "A basin with running water for washing food and dishes",
    icon: "droplet",
    imageUrl: "/assets/appliances/kitchen_sink_stainle_25720924.webp",
    isCommon: true,
    alternatives: null,
  },

  // COOKING
  {
    name: "Frying Pan/Skillet",
    category: "cooking",
    description:
      "A flat-bottomed pan used for frying, searing, and browning foods",
    icon: "circle",
    imageUrl: "/assets/appliances/frying_pan_skillet_c_f0c8dcea.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Saucepan (small, medium, large)",
    category: "cooking",
    description:
      "Deep pans with a handle used for cooking sauces, boiling, and more",
    icon: "circle",
    imageUrl: "/assets/appliances/saucepan_cooking_pot_9726d22d.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Stock Pot",
    category: "cooking",
    description:
      "A large, deep pot for making stocks, soups, and boiling pasta",
    icon: "circle",
    imageUrl: "/assets/appliances/stock_pot_large_cook_93226951.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Dutch Oven",
    category: "cooking",
    description: "A heavy pot with a tight lid for braising and slow cooking",
    icon: "circle",
    imageUrl: "/assets/appliances/dutch_oven_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Wok",
    category: "cooking",
    description: "A round-bottomed pan used for stir-frying and Asian cooking",
    icon: "circle",
    imageUrl: "/assets/appliances/wok_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Grill Pan",
    category: "cooking",
    description: "A pan with ridges that creates grill marks on food",
    icon: "grid",
    imageUrl: "/assets/appliances/grill_pan_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Roasting Pan",
    category: "cooking",
    description: "A large pan for roasting meats and vegetables in the oven",
    icon: "square",
    imageUrl: "/assets/appliances/roasting_pan_illustration.webp",
    isCommon: false,
    alternatives: null,
  },

  // BAKEWARE
  {
    name: "Baking Sheet",
    category: "bakeware",
    description: "A flat metal pan for baking cookies and roasting vegetables",
    icon: "square",
    imageUrl: "/assets/appliances/baking_sheet_metal_p_98785389.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Cake Pan",
    category: "bakeware",
    description: "A round or square pan for baking cakes",
    icon: "circle",
    imageUrl: "/assets/appliances/cake_pan_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Muffin Tin",
    category: "bakeware",
    description: "A pan with cups for baking muffins and cupcakes",
    icon: "grid",
    imageUrl: "/assets/appliances/muffin_tin_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Loaf Pan",
    category: "bakeware",
    description: "A rectangular pan for baking bread and meatloaf",
    icon: "square",
    imageUrl: "/assets/appliances/loaf_pan_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Pie Dish",
    category: "bakeware",
    description: "A shallow dish with sloped sides for baking pies",
    icon: "circle",
    imageUrl: "/assets/appliances/pie_dish_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Casserole Dish",
    category: "bakeware",
    description: "A deep dish for baking casseroles and gratins",
    icon: "square",
    imageUrl: "/assets/appliances/casserole_dish_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Cooling Rack",
    category: "bakeware",
    description: "A wire rack for cooling baked goods",
    icon: "grid",
    imageUrl: "/assets/appliances/cooling_rack_illustration.webp",
    isCommon: false,
    alternatives: null,
  },

  // SMALL APPLIANCES
  {
    name: "Blender",
    category: "small appliances",
    description:
      "An electric appliance for blending, pureeing, and making smoothies",
    icon: "zap",
    imageUrl: "/assets/appliances/blender_kitchen_appl_255f4b91.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Food Processor",
    category: "small appliances",
    description:
      "An electric appliance for chopping, slicing, and mixing ingredients",
    icon: "zap",
    imageUrl: "/assets/appliances/food_processor_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Stand Mixer",
    category: "small appliances",
    description: "A countertop mixer for baking with various attachments",
    icon: "zap",
    imageUrl: "/assets/appliances/stand_mixer_illustration.webp",
    isCommon: false,
    alternatives: ["Hand Mixer"],
  },
  {
    name: "Hand Mixer",
    category: "small appliances",
    description: "A handheld electric mixer for beating and whipping",
    icon: "zap",
    imageUrl: "/assets/appliances/hand_mixer_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Toaster",
    category: "small appliances",
    description: "An appliance for toasting bread and bagels",
    icon: "square",
    imageUrl: "/assets/appliances/toaster_kitchen_appl_cb1a790a.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Coffee Maker",
    category: "small appliances",
    description: "An appliance for brewing coffee",
    icon: "coffee",
    imageUrl: "/assets/appliances/coffee_maker_drip_ma_e3e71e0c.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Kettle",
    category: "small appliances",
    description: "An appliance for boiling water quickly",
    icon: "droplet",
    imageUrl: "/assets/appliances/electric_kettle_kitc_e1301f23.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Rice Cooker",
    category: "small appliances",
    description: "An appliance designed for cooking rice perfectly",
    icon: "zap",
    imageUrl: "/assets/appliances/rice_cooker_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Slow Cooker/Crock Pot",
    category: "small appliances",
    description: "An appliance for slow-cooking meals over several hours",
    icon: "clock",
    imageUrl: "/assets/appliances/slow_cooker_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Instant Pot/Pressure Cooker",
    category: "small appliances",
    description:
      "A multi-function cooker that uses pressure to cook food quickly",
    icon: "zap",
    imageUrl: "/assets/appliances/instant_pot_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Air Fryer",
    category: "small appliances",
    description:
      "An appliance that uses hot air circulation to cook crispy food",
    icon: "wind",
    imageUrl: "/assets/appliances/air_fryer_illustration.webp",
    isCommon: false,
    alternatives: ["Oven", "Convection Oven"],
  },
  {
    name: "Immersion Blender",
    category: "small appliances",
    description:
      "A handheld blender for pureeing soups and sauces directly in the pot",
    icon: "zap",
    imageUrl: "/assets/appliances/immersion_blender_illustration.webp",
    isCommon: false,
    alternatives: ["Blender", "Food Processor"],
  },

  // PREP TOOLS
  {
    name: "Cutting Board",
    category: "prep tools",
    description: "A board for cutting and preparing ingredients",
    icon: "square",
    imageUrl: "/assets/appliances/wooden_cutting_board_eb09edb9.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Chef's Knife",
    category: "prep tools",
    description: "A versatile knife for chopping, slicing, and dicing",
    icon: "minus",
    imageUrl: "/assets/appliances/chef_knife_kitchen_b_51a73073.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Paring Knife",
    category: "prep tools",
    description: "A small knife for peeling and detailed cutting work",
    icon: "minus",
    imageUrl: "/assets/appliances/paring_knife_small_k_b4e732c6.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Bread Knife",
    category: "prep tools",
    description: "A serrated knife for slicing bread and soft foods",
    icon: "minus",
    imageUrl: "/assets/appliances/bread_knife_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Kitchen Shears",
    category: "prep tools",
    description: "Scissors designed for cutting food items",
    icon: "scissors",
    imageUrl: "/assets/appliances/kitchen_shears_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Measuring Cups",
    category: "prep tools",
    description: "Cups for measuring dry and liquid ingredients",
    icon: "droplet",
    imageUrl: "/assets/appliances/measuring_cups_set_k_1cb9a872.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Measuring Spoons",
    category: "prep tools",
    description: "Spoons for measuring small quantities of ingredients",
    icon: "droplet",
    imageUrl: "/assets/appliances/measuring_spoons_set_0d5b82a9.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Mixing Bowls",
    category: "prep tools",
    description: "Bowls of various sizes for mixing ingredients",
    icon: "circle",
    imageUrl: "/assets/appliances/mixing_bowls_set_sta_dd927ee7.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Colander",
    category: "prep tools",
    description: "A bowl with holes for draining pasta and washing vegetables",
    icon: "circle",
    imageUrl: "/assets/appliances/colander_strainer_me_dade1c5a.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Grater",
    category: "prep tools",
    description: "A tool for shredding cheese, vegetables, and other foods",
    icon: "grid",
    imageUrl: "/assets/appliances/cheese_grater_box_gr_d907846d.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Peeler",
    category: "prep tools",
    description: "A tool for removing the skin from fruits and vegetables",
    icon: "minus",
    imageUrl: "/assets/appliances/vegetable_peeler_kit_7d0de638.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Can Opener",
    category: "prep tools",
    description: "A tool for opening canned foods",
    icon: "circle",
    imageUrl: "/assets/appliances/can_opener_manual_ki_ab972941.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Whisk",
    category: "prep tools",
    description: "A tool for beating eggs and mixing batters",
    icon: "activity",
    imageUrl: "/assets/appliances/whisk_metal_wire_kit_8b9a74e4.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Spatula",
    category: "prep tools",
    description: "A flat tool for flipping and lifting foods",
    icon: "minus",
    imageUrl: "/assets/appliances/spatula_turner_kitch_e8ea979a.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Wooden Spoon",
    category: "prep tools",
    description: "A heat-resistant spoon for stirring and cooking",
    icon: "minus",
    imageUrl: "/assets/appliances/wooden_spoon_cooking_f7d39556.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Tongs",
    category: "prep tools",
    description: "A tool for gripping and turning food",
    icon: "minus",
    imageUrl: "/assets/appliances/kitchen_tongs_metal__fe9ded4f.webp",
    isCommon: true,
    alternatives: null,
  },
  {
    name: "Ladle",
    category: "prep tools",
    description: "A deep-bowled spoon for serving soups and stews",
    icon: "droplet",
    imageUrl: "/assets/appliances/soup_ladle_metal_kit_b7b90103.webp",
    isCommon: true,
    alternatives: null,
  },

  // SPECIALTY
  {
    name: "Sous Vide",
    category: "specialty",
    description:
      "A precision cooking device that circulates water at exact temperatures",
    icon: "thermometer",
    imageUrl: "/assets/appliances/sous_vide_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Waffle Maker",
    category: "specialty",
    description: "An appliance for making waffles",
    icon: "grid",
    imageUrl: "/assets/appliances/waffle_maker_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Panini Press",
    category: "specialty",
    description: "A heated press for making grilled sandwiches",
    icon: "square",
    imageUrl: "/assets/appliances/panini_press_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Ice Cream Maker",
    category: "specialty",
    description: "An appliance for making homemade ice cream",
    icon: "circle",
    imageUrl: "/assets/appliances/ice_cream_maker_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Dehydrator",
    category: "specialty",
    description: "An appliance for drying fruits, vegetables, and meats",
    icon: "sun",
    imageUrl: "/assets/appliances/dehydrator_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Bread Machine",
    category: "specialty",
    description: "An appliance for automatically making bread",
    icon: "square",
    imageUrl: "/assets/appliances/bread_machine_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Pasta Machine",
    category: "specialty",
    description: "A manual or electric device for making fresh pasta",
    icon: "minus",
    imageUrl: "/assets/appliances/pasta_machine_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "KitchenAid Attachments",
    category: "specialty",
    description: "Various attachments for KitchenAid stand mixers",
    icon: "tool",
    imageUrl: "/assets/appliances/kitchenaid_attachments_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
  {
    name: "Thermomix",
    category: "specialty",
    description:
      "An all-in-one cooking appliance that weighs, chops, and cooks",
    icon: "zap",
    imageUrl: "/assets/appliances/thermomix_illustration.webp",
    isCommon: false,
    alternatives: null,
  },
];

export async function seedAppliances() {
  const pool = new pg.Pool({
    connectionString: process.env.DATABASE_URL,
  });

  const db = drizzle(pool);

  console.log("Seeding appliances...");

  try {
    await db.insert(appliances).values(APPLIANCES_DATA).onConflictDoNothing();
    console.log(`Seeded ${APPLIANCES_DATA.length} appliances successfully`);
  } catch (error) {
    console.error("Error seeding appliances:", error);
    throw error;
  } finally {
    await pool.end();
  }
}

if (require.main === module) {
  seedAppliances()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}
